// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aydufunbtppivgbwkzwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5ZHVmdW5idHBwaXZnYndrendxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjM3MTYsImV4cCI6MjA2NTIzOTcxNn0.2LRLYe_nGolW8HyaEQ9kQVqkzvmY1quJfq5MeMsnptc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);